### ISSUE TITLE
Options View not working in UITableViewCell

### ISSUE THREAD

**Issue by maclacerda** [Eke/EMEmojiableBtn#10]
Hello,

When I add a EMEmojiableBtn in a cell in a tableView the view that displays the options is not centered, but if I use the component on a controller, the view of options centralizes perfectly.

In [this](http://jmp.sh/M71Q0cZ) image I try to better explain the problem.

Have any suggestions to solve this?

Thanks

**Comment by bgoncal** [comment]
Im facing the same issue

**Comment by imanoj135** [comment]
Any luck on this?
