### ISSUE TITLE
Supporting various opening behaviours 

### ISSUE THREAD

**Issue by tomhoffen** [Eke/EMEmojiableBtn#5]
Hi, 

Are you planning to support different opening behaviours? 
For example, when the button is placed at the right side of the screen it should open to the left.
And when the button is close to the top margin it should open downwards (like Facebook).

Thank you!

**Comment by Eke** [comment]
Hello @tomhoffen, thanks for question ! Yes, it's very important feature and it's on todo list but i don't have a lot of free time right now. I will be happy if you can send PR for this, or even we can work together on this feature.

But anyway, i promise, this feature will be implemented asap

**Comment by tomhoffen** [comment]
Hi @Eke , 

Can you estimate when it will be implemented ?

Thanks

**Comment by tomhoffen** [comment]
Hi @Eke,
I looked over your code a bit and played with it locally and now if the button is located at the right side of the screen the menu is open to the left. 
I am new iOS developer, I am coming from very different field (firmware), So my fix is very ad hoc and the code is hard to maintain. I believe together we can find a better solution.

I'll be happy to share the code with you and work together to fix this.
In addition, later we can move to the second feature: when the button is close to the top margin it should open downwards.

Tom

**Comment by Eke** [comment]
@tomhoffen  This sounds great ! You can send PR and we can discuss changes together

**Comment by tomhoffen** [comment]
@Eke , I have never done this before. on dev branch?

**Comment by Eke** [comment]
@tomhoffen No problem, you can send it even to master

**Comment by tomhoffen** [comment]
@Eke No problem, I'll do it tomorrow.

**Comment by Eke** [comment]
@tomhoffen Hello, merged your PR, thanks !
