### ISSUE TITLE
without CocoaPods

### ISSUE THREAD

**Issue by Manueldjz** [Eke/EMEmojiableBtn#8]
it's possible to provide me the "file class"
I have a project without CocoaPods :(
am new on iOS
any one 
?
Thanks community

**Comment by tatocaster** [comment]
@Manueldjz  You can just download files and include as a project files in a separate group. then import header files. thats it. Good luck.

**Comment by Eke** [comment]
@Manueldjz you can just download it and drag&drop content of `Classes` folder into your project, after just include headers where you want.

I'm closing issue, but feel free to reopen it
